### ISSUE TITLE
Crew\Unsplash\Exception with error message: []

### ISSUE THREAD

**Issue by taduuda** [unsplash/unsplash-php#48]
Hi, I'm (still) getting a lot of Exceptions with an empty error message from the api. I've already had over 130 of these errors this month. Here is the error information I get:
```
2017-01-09 21:50:05.402  :  Error caller: functions at line 1212
2017-01-09 21:50:05.402  :  Error class: Crew\Unsplash\Exception
2017-01-09 21:50:05.402  :  Error message: []
2017-01-09 21:50:05.402  :  In: /path/php/vendor/crewlabs/unsplash/src/Endpoint.php(78)
2017-01-09 21:50:05.402  :  Stack trace:
2017-01-09 21:50:05.402  :  #0 /path/php/vendor/crewlabs/unsplash/src/User.php(19): Crew\Unsplash\Endpoint::__callStatic('get', Array)
2017-01-09 21:50:05.402  :  #1 /path/php/functions.php(1205): Crew\Unsplash\User::find('zimsurfa')
2017-01-09 21:50:05.402  :  #2 /path/php/get-liked.php(317): getUnsplashPhotoInfo('liked', '1', 25, 'oldest', 'zimsurfa')
2017-01-09 21:50:05.402  :  #3 {main}
```

I'm using a modified $user->likes function that allows me to use the 'order_by' parameter:
```
public function likes($page = 1, $per_page = 10, $order_by = 'latest')
    {
        if (! isset($this->likes["{$page}-{$per_page}-{$order_by}"])) {
            $likes = self::get("users/{$this->username}/likes", ['query' => ['page' => $page, 'per_page' => $per_page, 'order_by' => $order_by]]);

            $this->likes["{$page}-{$per_page}-{$order_by}"] = [
                'body' => self::getArray($likes->getBody(), __NAMESPACE__.'\\Photo'),
                'headers' => $likes->getHeaders()
            ];
        }

        return new ArrayObject(
            $this->likes["{$page}-{$per_page}-{$order_by}"]['body'],
            $this->likes["{$page}-{$per_page}-{$order_by}"]['headers']
        );
    }
```

And here is the function that is using this modified $user->likes function:
```
function getUnsplashPhotoInfo($syncmode,$page,$per_page='1',$order_by='latest',$username='') {
  if ($syncmode == 'featured') {
    UnsplashInit();
    try {
      $collectionData = Unsplash\CuratedCollection::find($page);
      $requestData = $collectionData->photos(1,1);
    } catch (Unsplash\Exception $e) {
      writeErrorLogEntry(basename(__FILE__,'.php'),__LINE__,$e);
    }
  } else if ($syncmode == 'liked') {
    UnsplashInit();
    try {
      $userData = Unsplash\User::find($username);
      $requestData = $userData->likes($page,$per_page,$order_by);
    } catch (Unsplash\Exception $e) {
      if ($e->getMessage() == '["Couldn\'t find User"]') {
        setErrUnsplashuser($username);
      }
      writeErrorLogEntry(basename(__FILE__,'.php'),__LINE__,$e);
    }
  }
  // Build photos array with required info
  foreach ($requestData as $photo) {
      $photos[] = array(
        'id' => $photo->id,
        'url' => $photo->urls['full'],
        'username' => strtolower($photo->user['username'])
      );
  }
  // Add filename to photos array
  foreach ($photos as $key => $value) {
    $photos[$key]['filename'] = buildUnsplashFilename($value);
  }
  if (!empty_array($photos)) {
    return $photos;
  } else {
    return false;
  }
}
```

The last piece of the puzzle is establishing the connection to the API:
```
function UnsplashInit($app_id) {
  if ($app_id !== false) {
    try {
      Unsplash\HttpClient::init(['applicationId' => $app_id]);
    } catch (Unsplash\Exception $e) {
      writeErrorLogEntry(basename(__FILE__,'.php'),__LINE__,$e);
    }
  }
}
```

I've tested this code on multiple servers, different versions of PHP and in different variants. Any idea on what is causing this issue and how to fix it?

Edit no. 1: The error log shows the $page being passed as a string ('1'). I've fixed that, but I'm still getting the error.

Edit no. 2: I ran a test with a simple GET request via Guzzle in order to find out whether this is a problem with the PHP client or the API itself. Looks like it is the client: not a single error in 8+ hours.
```
$client = new Client();
  $res = $client->request('GET', $api_url.'/users/'.$users[$choice].'/likes', [
    'headers' => ['Authorization'      => 'Client-ID '.$app_id],
    'query' => ['page' => 1, 'per_page' => 30, 'order_by' => 'oldest']
  ]);
$status = $res->getStatusCode();
$photos = json_decode($res->getBody(),true);
```

**Comment by aaronklaassen** [comment]
@taduuda What's the http response code you get with your "edit no 2" code? It's `200 OK`, right?

**Comment by taduuda** [comment]
@aaronklaassen Yes. Test ran 871 times today, got 200 and 30/30 photos every single time.

**Comment by taduuda** [comment]
I've written a custom wrapper that adds the HTTP status code to every exception. Getting some 403s and 500s.
```
2017-01-17 12:40:08.933  :  Error caller: functions at line 1189
2017-01-17 12:40:08.933  :  Error class: Diza\Unsplash\Exception
2017-01-17 12:40:08.933  :  Error message:  [500 Internal Server Error]
2017-01-17 12:40:08.933  :  In: /path/php/vendor/diza/unsplash/src/HttpClient.php(401)
2017-01-17 12:40:08.933  :  Stack trace:
2017-01-17 12:40:08.933  :  #0 /path/php/vendor/diza/unsplash/src/HttpClient.php(91): Diza\Unsplash\HttpClient->send_request('GET', 'users/zimsurfa/...', Array)
2017-01-17 12:40:08.933  :  #1 /path/php/functions.php(1183): Diza\Unsplash\HttpClient->user_likes('zimsurfa', 1, 25)
2017-01-17 12:40:08.933  :  #2 /path/php/get-liked.php(154): getUnsplashTotal('liked', 25, 'zimsurfa')
2017-01-17 12:40:08.933  :  #3 {main}
```
```
2017-01-17 13:25:01.936  :  Error caller: functions at line 1216
2017-01-17 13:25:01.936  :  Error class: Diza\Unsplash\Exception
2017-01-17 13:25:01.936  :  Error message:  [403 Forbidden]
2017-01-17 13:25:01.936  :  In: /path/php/vendor/diza/unsplash/src/HttpClient.php(401)
2017-01-17 13:25:01.936  :  Stack trace:
2017-01-17 13:25:01.936  :  #0 /www/htdocs/w014461b/aery.be/app/php/vendor/diza/unsplash/src/HttpClient.php(91): Diza\Unsplash\HttpClient->send_request('GET', 'users/masterstr...', Array)
2017-01-17 13:25:01.936  :  #1 /path/php/functions.php(1211): Diza\Unsplash\HttpClient->user_likes('masterstrike', 26, 25, 'oldest')
2017-01-17 13:25:01.936  :  #2 /path/php/get-liked.php(209): getUnsplashPhotoInfo('liked', 26, 25, 'oldest', 'masterstrike')
2017-01-17 13:25:01.936  :  #3 {main}
```

**Comment by aaronklaassen** [comment]
Are those 403's `Rate Limit Exceeded`?

**Comment by taduuda** [comment]
I don't know if they are. Wouldn't that be in the error messages though?
I do know that all my applications are well within their rate limits. Is it at all possible that this issue is related to the incorrect rate limit return values? That would at least explain the 400's.

**Comment by aaronklaassen** [comment]
@taduuda Yeah that's what I'm wondering.

Regardless though you're right: this is a bug; should be getting an error message.

**Comment by taduuda** [comment]
Getting the error messages to work might reveal the source of the problem. Let me know if you find anything or need any further info.

**Comment by taduuda** [comment]
Any news on this? I'm still getting some 503s on two different servers.

**Comment by lukechesser** [comment]
@taduuda @aaronklaassen any way to know if these are non-JSON responses being returned by the API?

Fastly sits between our API and can return HTML 503 responses on rare occasions where the backend times out. Our configuration is _supposed_ to be such that a response should always occur, whether it's a timeout 500 JSON response from the API or the actual response, before Fastly's timeout can kick in, but I wouldn't say it's _impossible_

**Comment by fbstim** [comment]
Just found this issue-- I've been using the API for the first time today, and it worked fine in the morning, but after lunch has been failing to find a (public) collection and throwing a `403` error with `[]` as the error message. I am pretty sure I'm not exceeding the rate limit since I'm just submitting requests by hand for testing.

**Comment by lukechesser** [comment]
@fbstim hmm, the previous 403 errors that @taduuda was getting were solved. Want to shoot us an email at api@unsplash.com?
